# Generated by Django 5.1.3 on 2025-02-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Customer Name",
                    ),
                ),
                (
                    "sale_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Sale Date"),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("credit", "Credit Card"),
                            ("debit", "Debit Card"),
                            ("pix", "PIX"),
                        ],
                        default="cash",
                        max_length=50,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Total"
                    ),
                ),
            ],
        ),
    ]
